from time import sleep
from userbot import CMD_HELP, bot
from userbot.events import register
from telethon import events
import asyncio


@register(outgoing=True, pattern="^.sayang$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        await e.edit("I LOVEE YOUUU 💕")
        await e.edit("💝💘💓💗")
        await e.edit("💞💕💗💘")
        await e.edit("💝💘💓💗")
        await e.edit("💞💕💗💘")
        await e.edit("💘💞💗💕")
        await e.edit("💘💞💕💗")
        await e.edit("SAYANG KAMU 💝💖💘")
        await e.edit("💝💘💓💗")
        await e.edit("💞💕💗💘")
        await e.edit("💘💞💕💗")
        await e.edit("SAYANG")
        await e.edit("KAMU")
        await e.edit("SELAMANYA 💕")
        await e.edit("💘💘💘💘")
        await e.edit("SAYANG")
        await e.edit("KAMU")
        await e.edit("SAYANG")
        await e.edit("KAMU")
        await e.edit("I LOVE YOUUUU")
        await e.edit("MY BABY")
        await e.edit("💕💞💘💝")
        await e.edit("💘💕💞💝")
        await e.edit("SAYANG KAMU💞")


@register(outgoing=True, pattern='^.dino(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("`DIN DINNN.....`")
    sleep(1)
    await typew.edit("`DINOOOOSAURUSSSSS!!`")
    sleep(1)
    await typew.edit("`🏃                        🦖`")
    await typew.edit("`🏃                       🦖`")
    await typew.edit("`🏃                      🦖`")
    await typew.edit("`🏃                     🦖`")
    await typew.edit("`🏃   `LARII`          🦖`")
    await typew.edit("`🏃                   🦖`")
    await typew.edit("`🏃                  🦖`")
    await typew.edit("`🏃                 🦖`")
    await typew.edit("`🏃                🦖`")
    await typew.edit("`🏃               🦖`")
    await typew.edit("`🏃              🦖`")
    await typew.edit("`🏃             🦖`")
    await typew.edit("`🏃            🦖`")
    await typew.edit("`🏃           🦖`")
    await typew.edit("`🏃WOARGH!   🦖`")
    await typew.edit("`🏃           🦖`")
    await typew.edit("`🏃            🦖`")
    await typew.edit("`🏃             🦖`")
    await typew.edit("`🏃              🦖`")
    await typew.edit("`🏃               🦖`")
    await typew.edit("`🏃                🦖`")
    await typew.edit("`🏃                 🦖`")
    await typew.edit("`🏃                  🦖`")
    await typew.edit("`🏃                   🦖`")
    await typew.edit("`🏃                    🦖`")
    await typew.edit("`🏃                     🦖`")
    await typew.edit("`🏃  Huh-Huh           🦖`")
    await typew.edit("`🏃                   🦖`")
    await typew.edit("`🏃                  🦖`")
    await typew.edit("`🏃                 🦖`")
    await typew.edit("`🏃                🦖`")
    await typew.edit("`🏃               🦖`")
    await typew.edit("`🏃              🦖`")
    await typew.edit("`🏃             🦖`")
    await typew.edit("`🏃            🦖`")
    await typew.edit("`🏃           🦖`")
    await typew.edit("`🏃          🦖`")
    await typew.edit("`🏃         🦖`")
    await typew.edit("`DIA SEMAKIN MENDEKAT!!!`")
    sleep(1)
    await typew.edit("`🏃       🦖`")
    await typew.edit("`🏃      🦖`")
    await typew.edit("`🏃     🦖`")
    await typew.edit("`🏃    🦖`")
    await typew.edit("`Dahlah Pasrah Aja`")
    sleep(1)
    await typew.edit("`🧎🦖`")
    sleep(2)
    await typew.edit("`-TAMAT-`")


@register(outgoing=True, pattern="^.gabut2$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        await e.edit("`Kawan kawan Aku mau cerita sedikit`")
        sleep(1)
        await e.edit("`Jadi Hari ini Aku lagi stressss anjing `")
        sleep(1)
        await e.edit("`GARA GARA GUA LIAT GRUP RAME`")
        sleep(1)
        await e.edit("`GILIRAN GUA NGETIK SEKETIKA SEPI`")
        sleep(1)
        await e.edit("`ANJING BANGET KAN YA`")
        sleep(1)
        await e.edit("`PADAHAL PAS GUA BLM DTG RAME BGT`")
        sleep(1)
        await e.edit("`PAS GUA MUNCUL SEPI BGT`")
        sleep(1)
        await e.edit("`ADA RASA INGIN KELUAR`")
        sleep(1)
        await e.edit("`TAPI KALIAN TEMAN AKU`")
        sleep(1)
        await e.edit("🥺")
        await e.edit("😭")
        await e.edit("😔")
        await e.edit("😖")
        await e.edit("`TAI BANGET POKOK NYA`")
        await e.edit("💩")
        await e.edit("...........................🚐")
        await e.edit("..........................🚐.")
        await e.edit("..............🛺.........🚐..")
        await e.edit("..............🛺........🚐...")
        await e.edit("..............🛺.......🚐....")
        await e.edit("..............🛺......🚐.....")
        await e.edit("..............🛺.....🚐......")
        await e.edit("..............🛺....🚐.......")
        await e.edit("..............🛺...🚐........")
        await e.edit("..............🛺.🚐..........")
        await e.edit("..............🛺🚐...........")
        await e.edit("............🚐🛺.............")
        await e.edit("..........🚐...🛺............")
        await e.edit(".........🚐.....🛺...........")
        await e.edit("........🚐.......🛺..........")
        await e.edit(".......🚐..........🛺........")
        await e.edit("......🚐.............🛺......")
        await e.edit(".....🚐...............🛺.....")
        await e.edit("....🚐..................🛺...")
        await e.edit("..🚐.....................🛺..")
        await e.edit(".🚐........................🛺")
        await e.edit("🚐...........................")
        await e.edit("...........................🚐")
        await e.edit("........🏠🏡🏘️............🚐.")
        await e.edit("........🏘️🏡🏠...........🚐..")
        await e.edit("........🏘️🏡🏠..........🚐...")
        await e.edit("........🏘️🏡🏠.........🚐....")
        await e.edit("........🏘️🏘️🏘️........🚐.....")
        await e.edit("........🏡🏠🏡.......🚐......")
        await e.edit("........🏘️🏡🏠......🚐.......")
        await e.edit("........🏘️🏡🏠.....🚐........")
        await e.edit("........🏘️🏡🏠....🚐.........")
        await e.edit("........🏘️🏡🏠...🚐..........")
        await e.edit("........🏘️🏡🏠..🚐...........")
        await e.edit("........🏘️🏡🏠.🚐............")
        await e.edit("........🏘️🏡🏠🚐.............")
        await e.edit("........🏘️🏡🚐🏠.............")
        await e.edit("........🏘️🚐🏡🏠.............")
        await e.edit("........🚐🏠🏡🏘️.............")
        await e.edit(".......🚐.🏠🏡🏡.............")
        await e.edit("......🚐..🏘️🏡🏠.............")
        await e.edit(".....🚐...🏘️🏡🏠.............")
        await e.edit("....🚐....🏘️🏠🏡.............")
        await e.edit("...🚐.....🏠🏡🏘️.............")
        await e.edit("..🚐......🏘️🏡🏠.............")
        await e.edit(".🚐.......🏘️🏡🏠.............")
        await e.edit("🚐........🏠🏡🏘️.............")
        await e.edit("...........................🚐")
        await e.edit("............🕌............🚐.")
        await e.edit("............🕌...........🚐..")
        await e.edit("............🕌..........🚐...")
        await e.edit("............🕌.........🚐....")
        await e.edit("............🕌........🚐.....")
        await e.edit("............🕌.......🚐......")
        await e.edit("............🕌......🚐.......")
        await e.edit("............🕌.....🚐........")
        await e.edit("............🕌....🚐.........")
        await e.edit("............🕌...🚐..........")
        await e.edit("............🕌..🚐...........")
        await e.edit("............🕌.🚐............")
        await e.edit("............🕌🚐.............")
        await e.edit("............🚐🕌.............")
        await e.edit("...........🚐.🕌.............")
        await e.edit("..........🚐..🕌.............")
        await e.edit(".........🚐...🕌.............")
        await e.edit("........🚐....🕌ᴬᴸᴸᴬᴴᵁ ᴬᴷᴮᴬᴿ²ˣ.")
        await e.edit("ᵂᴬᴴ ᴬᴰᶻᴬᴺ🚐....🕌.............")
        await e.edit("ˢᴴᴼᴸᴬᵀ ᴬᴴ🚐....🕌.............")
        await e.edit(".........🚐...🕌............")
        await e.edit("...........🚐.🕌............")
        await e.edit("............🚐🕌............")
        await e.edit("CERITANYA LAGI SHOLAT")
        await e.edit("KARNA SI UDIN TIDAK MAU CELAKA")
        await e.edit("SUNGGUH BERMANFAAT YAH GABUT NYA")
        await e.edit("KATA SI UDIN")
        await e.edit("SHOLAT LAH SEBELUM KAU DI SHOLATKAN")
        await e.edit("ᴬᴸᴴᴬᴹᴰᵁᴸᴵᴸᴸᴬᴴ ᴰᴴ ᴷᴱᴸᴬᴿ🚐🕌.............")
        await e.edit("ᴮᴵˢᴹᴵᴸᴸᴬᴴ..........🚐.🕌.............")
        await e.edit("...............🚐..🕌.............")
        await e.edit("..............🚐...🕌.............")
        await e.edit(".............🚐....🕌.............")
        await e.edit("............🚐.....🕌.............")
        await e.edit("...........🚐......🕌.............")
        await e.edit("..........🚐.......🕌.............")
        await e.edit("🏘️.......🚐........🕌.............")
        await e.edit("🏘️......🚐.........🕌.............")
        await e.edit("🏘️.....🚐..........🕌.............")
        await e.edit("🏘️....🚐...........🕌.............")
        await e.edit("🏘️...🚐............🕌.............")
        await e.edit("🏘️..🚐.............🕌.............")
        await e.edit("🏘️.🚐..............🕌.............")
        await e.edit("🏘️🚐...............🕌.............")
        await e.edit("..............................🚐🏘️")
        await e.edit(".............................🚐.🏘️")
        await e.edit("............................🚐..🏘️")
        await e.edit("...........................🚐...🏘️")
        await e.edit("..........................🚐....🏘️")
        await e.edit(".........................🚐.....🏘️")
        await e.edit("........................🚐......🏘️")
        await e.edit(".......................🚐.......🏘️")
        await e.edit(".....................🚐.........🏘️")
        await e.edit("....................🚐..........🏘️")
        await e.edit("...................🚐...........🏘️")
        await e.edit("..................🚐............🏘️")
        await e.edit(".................🚐.............🏘️")
        await e.edit("................🚐..............🏘️")
        await e.edit("...............🚐...............🏘️")
        await e.edit("..............🚐................🏘️")
        await e.edit(".............🚐.................🏘️")
        await e.edit("............🚐..................🏘️")
        await e.edit("...........🚐...................🏘️")
        await e.edit("..........🚐....................🏘️")
        await e.edit(".........🚐.....................🏘️")
        await e.edit("........🚐......................🏘️")
        await e.edit(".......🚐.......................🏘️")
        await e.edit("......🚐........................🏘️")
        await e.edit(".....🚐.........................🏘️")
        await e.edit("....🚐..........................🏘️")
        await e.edit("...🚐...........................🏘️")
        await e.edit("..🚐............................🏘️")
        await e.edit(".🚐.............................🏘️")
        await e.edit("🚐..............................🏘️")
        await e.edit("🐢                       🚶")
        await e.edit("🐢                      🚶")
        await e.edit("🐢                     🚶")
        await e.edit("🐢                    🚶")
        await e.edit("🐢                   🚶")
        await e.edit("🐢                  🚶")
        await e.edit("🐢                 🚶")
        await e.edit("🐢                🚶")
        await e.edit("🐢               🚶")
        await e.edit("🐢              🚶")
        await e.edit("🐢             🚶")
        await e.edit("🐢            🚶")
        await e.edit("🐢           🚶")
        await e.edit("🐢          🚶")
        await e.edit("🐢         🚶")
        await e.edit("🐢        🚶")
        await e.edit("🐢       🚶")
        await e.edit("🐢      🚶")
        await e.edit("🐢     🚶")
        await e.edit("🐢    🚶")
        await e.edit("🐢   🚶")
        await e.edit("🐢  🚶")
        await e.edit("🐢 🚶")
        await e.edit("🐢🚶")
        await e.edit("🚶🐢")
        await e.edit("🚶 🐢")
        await e.edit("🚶  🐢")
        await e.edit("🚶   🐢")
        await e.edit("🚶    🐢")
        await e.edit("🚶     🐢")
        await e.edit("🚶      🐢")
        await e.edit("🚶       🐢")
        await e.edit("🚶        🐢")
        await e.edit("🚶         🐢")
        await e.edit("🚶          🐢")
        await e.edit("🚶           🐢")
        await e.edit("🚶            🐢")
        await e.edit("🚶             🐢")
        await e.edit("🚶              🐢")
        await e.edit("🚶               🐢")
        await e.edit("🚶                🐢")
        await e.edit("🚶                 🐢")
        await e.edit("🚶                  🐢")
        await e.edit("🚶                   🐢")
        await e.edit("🚶                    🐢")
        await e.edit("🚶                     🐢")
        await e.edit("🚶                      🐢")
        await e.edit("🚶                       🐢")
        await e.edit("🚶                        🐢")
        await e.edit("🚶                         🐢")
        await e.edit("🚶                          🐢")
        await e.edit("🚶                           🐢")
        await e.edit("🚶                            🐢")
        await e.edit("🚶                             🐢")
        await e.edit("🚶                              🐢")
        await e.edit("🚶                               🐢")
        await e.edit("🚶                                🐢")
        await e.edit("🐢                       🚶")
        await e.edit("🐢                      🚶")
        await e.edit("🐢                     🚶")
        await e.edit("🐢                    🚶")
        await e.edit("🐢                   🚶")
        await e.edit("🐢                  🚶")
        await e.edit("🐢                 🚶")
        await e.edit("🐢                🚶")
        await e.edit("🐢               🚶")
        await e.edit("🐢              🚶")
        await e.edit("🐢             🚶")
        await e.edit("🐢            🚶")
        await e.edit("🐢           🚶")
        await e.edit("🐢          🚶")
        await e.edit("🐢         🚶")
        await e.edit("🐢        🚶")
        await e.edit("🐢       🚶")
        await e.edit("🐢      🚶")
        await e.edit("🐢     🚶")
        await e.edit("🐢    🚶")
        await e.edit("🐢   🚶")
        await e.edit("🐢  🚶")
        await e.edit("🐢 🚶")
        await e.edit("🐢🚶")
        await e.edit("🚶🐢")
        await e.edit("🚶 🐢")
        await e.edit("🚶  🐢")
        await e.edit("🚶   🐢")
        await e.edit("🚶    🐢")
        await e.edit("🚶     🐢")
        await e.edit("🚶      🐢")
        await e.edit("🚶       🐢")
        await e.edit("🚶        🐢")
        await e.edit("🚶         🐢")
        await e.edit("🚶          🐢")
        await e.edit("🚶           🐢")
        await e.edit("🚶            🐢")
        await e.edit("🚶             🐢")
        await e.edit("🚶              🐢")
        await e.edit("🚶               🐢")
        await e.edit("🚶                🐢")
        await e.edit("🚶                 🐢")
        await e.edit("🚶                  🐢")
        await e.edit("🚶                   🐢")
        await e.edit("🚶                    🐢")
        await e.edit("🚶                     🐢")
        await e.edit("🚶                      🐢")
        await e.edit("🚶                       🐢")
        await e.edit("🚶                        🐢")
        await e.edit("🚶                         🐢")
        await e.edit("🚶                          🐢")
        await e.edit("🚶                           🐢")
        await e.edit("🚶                            🐢")
        await e.edit("🚶                             🐢")
        await e.edit("🚶                              🐢")
        await e.edit("🚶                               🐢")
        await e.edit("🚶                                🐢")
        await e.edit("`NGAPAIN DI LIAT?😒😡`")


@register(outgoing=True, pattern="^.gabut$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        await e.edit("`PERNAAHHHHH KAHHH KAUUU MENGIRA`")
        await e.edit("`SEPEEERTIIIII APAAAA BENTUKKKKKKK CINTAAAA`")
        await e.edit("`RAMBUUUT WARNAAA WARNII`")
        await e.edit("`BAGAI GULALI`")
        await e.edit("`IMUUUTTTTT LUCUUU`")
        await e.edit("`WALAAUUUU TAK TERLALU TINGGI`")
        await e.edit("`GW GABUUTTTT`")
        await e.edit("`EMMMM BACOTNYA`")
        await e.edit("`GABUTTTT WOI GABUT`")
        await e.edit("🙈🙈🙈🙈")
        await e.edit("🙉🙉🙉🙉")
        await e.edit("🙈🙈🙈🙈")
        await e.edit("🙉🙉🙉🙉")
        await e.edit("`CILUUUKKK BAAAAA`")
        await e.edit("🙉🙉🙉🙉")
        await e.edit("🐢                       🚶")
        await e.edit("🐢                      🚶")
        await e.edit("🐢                     🚶")
        await e.edit("🐢                    🚶")
        await e.edit("🐢                   🚶")
        await e.edit("🐢                  🚶")
        await e.edit("🐢                 🚶")
        await e.edit("🐢                🚶")
        await e.edit("🐢               🚶")
        await e.edit("🐢              🚶")
        await e.edit("🐢             🚶")
        await e.edit("🐢            🚶")
        await e.edit("🐢           🚶")
        await e.edit("🐢          🚶")
        await e.edit("🐢         🚶")
        await e.edit("🐢        🚶")
        await e.edit("🐢       🚶")
        await e.edit("🐢      🚶")
        await e.edit("🐢     🚶")
        await e.edit("🐢    🚶")
        await e.edit("🐢   🚶")
        await e.edit("🐢  🚶")
        await e.edit("🐢 🚶")
        await e.edit("🐢🚶")
        await e.edit("🚶🐢")
        await e.edit("🚶 🐢")
        await e.edit("🚶  🐢")
        await e.edit("🚶   🐢")
        await e.edit("🚶    🐢")
        await e.edit("🚶     🐢")
        await e.edit("🚶      🐢")
        await e.edit("🚶       🐢")
        await e.edit("🚶        🐢")
        await e.edit("🚶         🐢")
        await e.edit("🚶          🐢")
        await e.edit("🚶           🐢")
        await e.edit("🚶            🐢")
        await e.edit("🚶             🐢")
        await e.edit("🚶              🐢")
        await e.edit("🚶               🐢")
        await e.edit("🚶                🐢")
        await e.edit("🚶                 🐢")
        await e.edit("🚶                  🐢")
        await e.edit("🚶                   🐢")
        await e.edit("🚶                    🐢")
        await e.edit("🚶                     🐢")
        await e.edit("🚶                      🐢")
        await e.edit("🚶                       🐢")
        await e.edit("🚶                        🐢")
        await e.edit("🚶                         🐢")
        await e.edit("🚶                          🐢")
        await e.edit("🚶                           🐢")
        await e.edit("🚶                            🐢")
        await e.edit("🚶                             🐢")
        await e.edit("🚶                              🐢")
        await e.edit("🚶                               🐢")
        await e.edit("🚶                                🐢")
        await e.edit("🚶                                 🐢")
        await e.edit("`AHHH MANTAP`")
        await e.edit("🙉")
        await e.edit("🙈")
        await e.edit("🙉")
        await e.edit("🙈")
        await e.edit("🙉")
        await e.edit("😂")
        await e.edit("🐢                       🚶")
        await e.edit("🐢                      🚶")
        await e.edit("🐢                     🚶")
        await e.edit("🐢                    🚶")
        await e.edit("🐢                   🚶")
        await e.edit("🐢                  🚶")
        await e.edit("🐢                 🚶")
        await e.edit("🐢                🚶")
        await e.edit("🐢               🚶")
        await e.edit("🐢              🚶")
        await e.edit("🐢             🚶")
        await e.edit("🐢            🚶")
        await e.edit("🐢           🚶")
        await e.edit("🐢          🚶")
        await e.edit("🐢         🚶")
        await e.edit("🐢        🚶")
        await e.edit("🐢       🚶")
        await e.edit("🐢      🚶")
        await e.edit("🐢     🚶")
        await e.edit("🐢    🚶")
        await e.edit("🐢   🚶")
        await e.edit("🐢  🚶")
        await e.edit("🐢 🚶")
        await e.edit("🐢🚶")
        await e.edit("🚶🐢")
        await e.edit("🚶 🐢")
        await e.edit("🚶  🐢")
        await e.edit("🚶   🐢")
        await e.edit("🚶    🐢")
        await e.edit("🚶     🐢")
        await e.edit("🚶      🐢")
        await e.edit("🚶       🐢")
        await e.edit("🚶        🐢")
        await e.edit("🚶         🐢")
        await e.edit("🚶          🐢")
        await e.edit("🚶           🐢")
        await e.edit("🚶            🐢")
        await e.edit("🚶             🐢")
        await e.edit("🚶              🐢")
        await e.edit("🚶               🐢")
        await e.edit("🚶                🐢")
        await e.edit("🚶                 🐢")
        await e.edit("🚶                  🐢")
        await e.edit("🚶                   🐢")
        await e.edit("🚶                    🐢")
        await e.edit("🚶                     🐢")
        await e.edit("🚶                      🐢")
        await e.edit("🚶                       🐢")
        await e.edit("🚶                        🐢")
        await e.edit("🚶                         🐢")
        await e.edit("🚶                          🐢")
        await e.edit("🚶                           🐢")
        await e.edit("🚶                            🐢")
        await e.edit("🚶                             🐢")
        await e.edit("🚶                              🐢")
        await e.edit("🚶                               🐢")
        await e.edit("🚶                                🐢")
        await e.edit("🐢                       🚶")
        await e.edit("🐢                      🚶")
        await e.edit("🐢                     🚶")
        await e.edit("🐢                    🚶")
        await e.edit("🐢                   🚶")
        await e.edit("🐢                  🚶")
        await e.edit("🐢                 🚶")
        await e.edit("🐢                🚶")
        await e.edit("🐢               🚶")
        await e.edit("🐢              🚶")
        await e.edit("🐢             🚶")
        await e.edit("🐢            🚶")
        await e.edit("🐢           🚶")
        await e.edit("🐢          🚶")
        await e.edit("🐢         🚶")
        await e.edit("🐢        🚶")
        await e.edit("🐢       🚶")
        await e.edit("🐢      🚶")
        await e.edit("🐢     🚶")
        await e.edit("🐢    🚶")
        await e.edit("🐢   🚶")
        await e.edit("🐢  🚶")
        await e.edit("🐢 🚶")
        await e.edit("🐢🚶")
        await e.edit("🚶🐢")
        await e.edit("🚶 🐢")
        await e.edit("🚶  🐢")
        await e.edit("🚶   🐢")
        await e.edit("🚶    🐢")
        await e.edit("🚶     🐢")
        await e.edit("🚶      🐢")
        await e.edit("🚶       🐢")
        await e.edit("🚶        🐢")
        await e.edit("🚶         🐢")
        await e.edit("🚶          🐢")
        await e.edit("🚶           🐢")
        await e.edit("🚶            🐢")
        await e.edit("🚶             🐢")
        await e.edit("🚶              🐢")
        await e.edit("🚶               🐢")
        await e.edit("🚶                🐢")
        await e.edit("🚶                 🐢")
        await e.edit("🚶                  🐢")
        await e.edit("🚶                   🐢")
        await e.edit("🚶                    🐢")
        await e.edit("🚶                     🐢")
        await e.edit("🚶                      🐢")
        await e.edit("🚶                       🐢")
        await e.edit("🚶                        🐢")
        await e.edit("🚶                         🐢")
        await e.edit("🚶                          🐢")
        await e.edit("🚶                           🐢")
        await e.edit("🚶                            🐢")
        await e.edit("🚶                             🐢")
        await e.edit("🚶                              🐢")
        await e.edit("🚶                               🐢")
        await e.edit("🚶                                🐢")
        await e.edit("🐢                       🚶")
        await e.edit("🐢                      🚶")
        await e.edit("🐢                     🚶")
        await e.edit("🐢                    🚶")
        await e.edit("🐢                   🚶")
        await e.edit("🐢                  🚶")
        await e.edit("🐢                 🚶")
        await e.edit("🐢                🚶")
        await e.edit("🐢               🚶")
        await e.edit("🐢              🚶")
        await e.edit("🐢             🚶")
        await e.edit("🐢            🚶")
        await e.edit("🐢           🚶")
        await e.edit("🐢          🚶")
        await e.edit("🐢         🚶")
        await e.edit("🐢        🚶")
        await e.edit("🐢       🚶")
        await e.edit("🐢      🚶")
        await e.edit("🐢     🚶")
        await e.edit("🐢    🚶")
        await e.edit("🐢   🚶")
        await e.edit("🐢  🚶")
        await e.edit("🐢 🚶")
        await e.edit("🐢🚶")
        await e.edit("🚶🐢")
        await e.edit("🚶 🐢")
        await e.edit("🚶  🐢")
        await e.edit("🚶   🐢")
        await e.edit("🚶    🐢")
        await e.edit("🚶     🐢")
        await e.edit("🚶      🐢")
        await e.edit("🚶       🐢")
        await e.edit("🚶        🐢")
        await e.edit("🚶         🐢")
        await e.edit("🚶          🐢")
        await e.edit("🚶           🐢")
        await e.edit("🚶            🐢")
        await e.edit("🚶             🐢")
        await e.edit("🚶              🐢")
        await e.edit("🚶               🐢")
        await e.edit("🚶                🐢")
        await e.edit("🚶                 🐢")
        await e.edit("🚶                  🐢")
        await e.edit("🚶                   🐢")
        await e.edit("🚶                    🐢")
        await e.edit("🚶                     🐢")
        await e.edit("🚶                      🐢")
        await e.edit("🚶                       🐢")
        await e.edit("🚶                        🐢")
        await e.edit("🚶                         🐢")
        await e.edit("🚶                          🐢")
        await e.edit("🚶                           🐢")
        await e.edit("🚶                            🐢")
        await e.edit("🚶                             🐢")
        await e.edit("🚶                              🐢")
        await e.edit("🚶                               🐢")
        await e.edit("🚶                                🐢")
        await e.edit("`GABUT`")


@register(outgoing=True, pattern="^.mf$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        await e.edit("`mf g dl` **ミ(ノ;_ _)ノ=3** ")


@bot.on(events.NewMessage(pattern=r"\.(.*)", outgoing=True))
async def _(event):

    if event.fwd_from:

        return

    animation_interval = 2

    animation_ttl = range(0, 11)

    input_str = event.pattern_match.group(1)

    if input_str == "cinta":

        await event.edit(input_str)

        animation_chars = [
            "`Connecting Ke Server Cinta`",
            "`Mencari Target Cinta`",
            "`Mengirim Cintaku.. 0%\n▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 4%\n█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 8%\n██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 20%\n█████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 36%\n█████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 52%\n█████████████▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 84%\n█████████████████████▒▒▒▒ `",
            "`Mengirim Cintaku.. 100%\n█████████CINTAKU███████████ `",
            f"`Cintaku Sekarang Sepenuhnya Terkirim Padamu, Dan Sekarang Aku Sangat Mencintai Mu, I Love You 💞`"]

        for i in animation_ttl:

            await asyncio.sleep(animation_interval)

            await event.edit(animation_chars[i % 11])


@register(outgoing=True, pattern="^.sange$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        await e.edit("SAYANGGGGGGGGG 💕")
        sleep(1)
        await e.edit("💝💘💓💗")
        sleep(1)
        await e.edit("💞💕💗💘")
        sleep(1)
        await e.edit("💝💘💓💗")
        sleep(1)
        await e.edit("💞💕💗💘")
        sleep(1)
        await e.edit("💘💞💗💕")
        sleep(1)
        await e.edit("💘💞💕💗")
        sleep(1)
        await e.edit("EMMMMMM🥺🥺🥺")
        sleep(1)
        await e.edit("💝💘💓💗")
        await e.edit("💞💕💗💘")
        await e.edit("💘💞💕💗")
        await e.edit("SAYANG")
        sleep(1)
        await e.edit("AKU 👉👈")
        sleep(1)
        await e.edit("SANGE 👉👈 😘😘")
        sleep(1)
        await e.edit("💘💘💘💘")
        sleep(1)
        await e.edit("SAYANG")
        sleep(1)
        await e.edit("AYO NGEWE🤭🤭")
        sleep(1)
        await e.edit("PLISS🥺🥺")
        sleep(1)
        await e.edit("AKU SANGE😋😋")
        sleep(1)
        await e.edit("I LOVE YOUUUU")
        sleep(1)
        await e.edit("AH AH AH BEIBB")
        sleep(1)
        await e.edit("💦💦💦💦")
        sleep(1)
        await e.edit("OH BABY")
        sleep(1)
        await e.edit("AKU SAYANG KAMU💞")


@register(outgoing=True, pattern="^.orgil(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("`ANJING ADA ORANG GILA.....`")
    sleep(1)
    await typew.edit("`ORANG GILAAAAAA!!`")
    sleep(1)
    await typew.edit("`🏃                        🤸`")
    await typew.edit("`🏃                       🤸`")
    await typew.edit("`🏃                      👨‍🦽`")
    await typew.edit("`🏃                     ⛹️`")
    await typew.edit("`🏃   `LARII`          🤾`")
    await typew.edit("`🏃                   🤾`")
    await typew.edit("`🏃                  🤾`")
    await typew.edit("`🏃                 🤾`")
    await typew.edit("`🏃                🤾`")
    await typew.edit("`🏃               🤺`")
    await typew.edit("`🏃              🏊`")
    await typew.edit("`🏃             🏊`")
    await typew.edit("`🏃            🏄`")
    await typew.edit("`🏃           🤾`")
    await typew.edit("`🏃PULUPULU   🧚`")
    await typew.edit("`🏃           ⛹️`")
    await typew.edit("`🏃            ⛹️`")
    await typew.edit("`🏃             🤺`")
    await typew.edit("`🏃              🥴`")
    await typew.edit("`🏃               🏃`")
    await typew.edit("`🏃                🏃`")
    await typew.edit("`🏃                 🤸`")
    await typew.edit("`🏃                  🤸`")
    await typew.edit("`🏃                   🤸`")
    await typew.edit("`🏃                    🤸`")
    await typew.edit("`🏃                     ⛹️`")
    await typew.edit("`🏃  Huh-Huh           🏃`")
    await typew.edit("`🏃                   🤑`")
    await typew.edit("`🏃                  🙈`")
    await typew.edit("`🏃                 ⛹️`")
    await typew.edit("`🏃                🏃`")
    await typew.edit("`🏃               🤴`")
    await typew.edit("`🏃              🐖`")
    await typew.edit("`🏃             🐖`")
    await typew.edit("`🏃            🥴`")
    await typew.edit("`🏃           🥴`")
    await typew.edit("`🏃          🤡`")
    await typew.edit("`🏃         🤭`")
    await typew.edit("`CAPE BANGET ANJING!!!`")
    sleep(1)
    await typew.edit("`🏃       🏃`")
    await typew.edit("`🏃      🤾`")
    await typew.edit("`🏃     🏃`")
    await typew.edit("`🏃    🏃`")
    await typew.edit("`Dahlah Pasrah Aja`")
    sleep(1)
    await typew.edit("`🧎🐖`")
    sleep(2)
    await typew.edit("`-TAMAT-`")


@register(outgoing=True, pattern='^.gblk(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("WOI GOBLOK!!!")
    sleep(2)
    await typew.edit("KOK LU GOBLOK BANGET SIH ANJING")
    sleep(2)
    await typew.edit("UDAH DI SIA SIA IN, DAN GA DI ANGGAP")
    sleep(2)
    await typew.edit("MASIH AJA LU PERTAHANIN, GOBLOK!!!!")
    sleep(2)
    await typew.edit("UDAH LAH ANJING,GAOSAH KAYA GTU")
    sleep(2)
    await typew.edit("JAUHIN AJA AJG, BOCAH KYA DIA MAH")
    sleep(2)
    await typew.edit("TINGGALIN AJA YA AJG!!!!")


@register(outgoing=True, pattern="^.ass(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("`Salam dulu biar sopan....`")
    sleep(2)
    await typew.edit("`A`")
    await typew.edit("`As`")
    await typew.edit("`Ass`")
    await typew.edit("`Assa`")
    await typew.edit("`Assal`")
    await typew.edit("`Assala`")
    await typew.edit("`Assalam`")
    await typew.edit("`Assalamu`")
    await typew.edit("`Assalamu'a`")
    await typew.edit("`Assalamu'al`")
    await typew.edit("`Assalamu'ala`")
    await typew.edit("`Assalamu'alai`")
    await typew.edit("`Assalamu'alaik`")
    await typew.edit("`Assalamu'alaiku`")
    await typew.edit("`Assalamu'alaikum`")
    sleep(3)
    await typew.edit("**YANG GA JAWAB, FIX ATHEISS!!**")
# Create by myself @ram-ubot


CMD_HELP.update({
    "animasi5":
    "𝘾𝙤𝙢𝙢𝙖𝙣𝙙: `.gabut` | `.gabut2` | `.dino`\
    \n↳ : Dikala gabut, yaaa pake aja xixixi.\
    \n\n𝘾𝙤𝙢𝙢𝙖𝙣𝙙: `.cinta`\
    \n↳ : mengirim cintamu ke seseorang.\
    \n\n𝘾𝙤𝙢𝙢𝙖𝙣𝙙: `.sayang`\
    \n↳ : Berubah menjadi kadal."
})

CMD_HELP.update({
    "animasi6": 
    "𝘾𝙤𝙢𝙢𝙖𝙣𝙙: `.orgil`\
    \n↳ : ntahlah coba aja.\
    \n\n𝘾𝙤𝙢𝙢𝙖𝙣𝙙: `.gblk`\
    \n↳ : cobain aja.\
    \n\n𝘾𝙤𝙢𝙢𝙖𝙣𝙙: `.sange` :\
    \n↳ : cobalah sndiri bodoh.\
    \n\n𝘾𝙤𝙢𝙢𝙖𝙣𝙙: `.ass`\
    \n↳ : salam dulu biar sopan."
})
